<div id="footer">
	<hr />
	<a name="foot"></a>
    <div class="footerContent">
        <p><strong>Fresh tweets from <span class="highlight">@titojackson</span> &bull;</strong> <a href="http://twitter.com/titojackson" target="_blank">Follow me</a></p>
        <ul id="twitter_update_list3"></ul>
        
		<div class="clrLft divider"><hr /></div>
        
        <p><span class="highlight">The Committee to Elect Tito Jackson</span> &bull;  37 Schuyler St &bull; Dorchester, MA, 02121 &bull; 781-507-3987 &bull; <a href="mailto:tito4boston@gmail.com">tito4boston@gmail.com</a></p>
            
        <div class="divider">&nbsp;</div> 

    </div><!-- /.footerContent -->
</div><!-- /#footer-->

<script type="text/javascript" src="http://titojacksonforboston.com/scripts/js/twitter.js"></script>
<script type="text/javascript" src="http://twitter.com/statuses/user_timeline/titojackson.json?callback=twitterCallback2&amp;count=1"></script>
<script type="text/javascript" src="http://twitter.com/statuses/user_timeline/titojackson.json?callback=twitterCallback3&amp;count=3"></script>
<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
try {
var pageTracker = _gat._getTracker("UA-7217002-5");
pageTracker._trackPageview();
} catch(err) {}</script>