<div id="header">
    <div class="headerContent">
        <h1 class="fltLft"><a href="http://www.titojacksonforboston.com">Tito Jackson for Boston City Council</a></h1>
        <div class="fltRgt">
            <span class="btn black fltLft"><a href="http://www.titojacksonforboston.com/get-involved/">Get Involved</a></span>
            <form action="https://www.paypal.com/cgi-bin/webscr" class="fltLft" method="post" target="_blank">
                <input type="hidden" name="cmd" value="_s-xclick"/>
                <input type="hidden" name="hosted_button_id" value="6151867"/>
                <input type="submit" title="Donate to Our Cause with PayPal" value="Donate Now" />
            </form>
        </div>
        
        <hr />
        
        <a name="navigation"></a>
        <ul id="nav" class="clr">
            <li<?php if($thisPage=="meettito") echo " id=\"current\""; ?>><a href="http://www.titojacksonforboston.com/meet-tito/">Meet Tito</a></li>
            <li<?php if($thisPage=="issues") echo " id=\"current\""; ?>><a href="http://www.titojacksonforboston.com/the-issues/">The Issues</a></li>
            <li<?php if($thisPage=="media") echo " id=\"current\""; ?> class="inactive"><a name="media">Media</a></li>
            <li<?php if($thisPage=="getinvolved") echo " id=\"current\""; ?>><a href="http://www.titojacksonforboston.com/get-involved/">Get Involved</a></li>
            <li><a href="https://www.paypal.com/cgi-bin/webscr?cmd=_donations&amp;business=tito4boston@gmail.com&amp;item_name=Committee+to+Elect+Tito+Jackson&amp;currency_code=USD" target="_blank">Make A Donation</a></li>
            <li<?php if($thisPage=="contact") echo " id=\"current\""; ?>><a href="http://www.titojacksonforboston.com/contact-us/">Contact Us</a></li>
            <li<?php if($thisPage=="blog") echo " id=\"current\""; ?> class="inactive last"><a name="blog">Blog</a></li>
        </ul>